include:
  - path: docker-compose.yml

services:
  pgweb:
    image: sosedoff/pgweb
    ports:
      - "8085:8081"
    environment:
      - DATABASE_URL=postgres://hapi:${POSTGRES_HAPI_PASSWORD}@postgres-hapi:5432/hapi?sslmode=disable
    depends_on:
      postgres-hapi:
        condition: service_healthy

  build-fhir-bundle-demo:
    image: bedasoftware/fhirsnake:latest
    command:
      - export
      - --output
      - /app/fhir-bundles/fhirBundle.json
      - --external-questionnaire-fce-fhir-converter-url
      - http://questionnaire-fce-fhir-converter:3000/to-fhir
      - --embed-mapping
    depends_on:
      questionnaire-fce-fhir-converter:
        condition: service_healthy
    volumes:
      - ./resources/fhir-seeds-de:/app/resources
      - ./resources/fhir-bundles-demo:/app/fhir-bundles

  upload-fhir-bundle-demo:
    image: curlimages/curl
    depends_on:
      hapi-fhir-ready:
        condition: service_completed_successfully
      build-fhir-bundle-demo:
        condition: service_completed_successfully
    working_dir: /app/resources/fhir-bundles
    command:
      - "sh"
      - "-c"
      - "curl -X POST 'http://hapi-fhir:8080/fhir' -H 'Content-Type: application/json' -d @fhirBundle.json"
      - --external-questionnaire-fce-fhir-converter-url
      - http://questionnaire-fce-fhir-converter:3000/to-fhir
    volumes:
      - ./resources/fhir-bundles-demo/:/app/resources/fhir-bundles

  watch-fhir-seeds:
    image: bedasoftware/fhirsnake:latest
    command:
      - watch
      - --external-fhir-server-url
      - http://hapi-fhir:8080/fhir
      - --external-questionnaire-fce-fhir-converter-url
      - http://questionnaire-fce-fhir-converter:3000/to-fhir
      - --embed-mapping
    depends_on:
      hapi-fhir-ready:
        condition: service_completed_successfully
      questionnaire-fce-fhir-converter:
        condition: service_healthy
    volumes:
      - ./resources/fhir-seeds:/app/resources

  watch-fhir-seeds-demo:
    image: bedasoftware/fhirsnake:latest
    command:
      - watch
      - --external-fhir-server-url
      - http://hapi-fhir:8080/fhir
      - --external-questionnaire-fce-fhir-converter-url
      - http://questionnaire-fce-fhir-converter:3000/to-fhir
      - --embed-mapping
    depends_on:
      hapi-fhir-ready:
        condition: service_completed_successfully
      questionnaire-fce-fhir-converter:
        condition: service_healthy
    volumes:
      - ./resources/fhir-seeds-demo:/app/resources
